name: Hello world

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run pwd
      run: pwd
    - name: Run cd
      run: cd ../
    - name: Run pwd
      run: pwd
    - name: Run cd
      run: cd ../
    - name: Run pwd
      run: pwd
    - name: Run ls -al
      run: ls -al
    
